version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: techanal-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5502:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Server (Hono API)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: techanal-server
    ports:
      - "5500:8787"
      - "9229:9229"
    environment:
      NODE_ENV: development
      PORT: 8787
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
      FIREBASE_PROJECT_ID: demo-project
      AI_PROVIDER: mock
      AI_TIMEOUT: 30000
      AI_MAX_TOKENS: 1000
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./thumbnails:/app/thumbnails
    depends_on:
      postgres:
        condition: service_healthy
    command: pnpm run dev:debug

  # Frontend (React + Vite)
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    container_name: techanal-ui
    ports:
      - "5501:5173"
    environment:
      VITE_API_URL: http://server:8787
      VITE_USE_FIREBASE_EMULATOR: "false"
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - server
    command: pnpm run dev -- --host 0.0.0.0 --port 5173

  # Firebase Auth Emulator
  firebase:
    image: node:18-alpine
    container_name: techanal-firebase
    ports:
      - "5503:5603"
      - "5504:5604"
    environment:
      FIREBASE_PROJECT_ID: demo-project
    volumes:
      - ./data/firebase-emulator:/firebase-data
      - ./firebase.json:/firebase.json
    working_dir: /app
    command: >
      sh -c "
        npm install -g firebase-tools &&
        firebase emulators:start --only auth --project demo-project --export-on-exit=/firebase-data --import=/firebase-data
      "

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: techanal-network
