global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # TechAnal Backend Server
  - job_name: 'techanal-backend'
    static_configs:
      - targets: ['server:8787']
    metrics_path: '/api/v1/performance/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # TechAnal Frontend
  - job_name: 'techanal-frontend'
    static_configs:
      - targets: ['ui:80']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 60s
    scrape_timeout: 10s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter (if deployed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 60s
    scrape_timeout: 10s

  # Custom TechAnal Metrics
  - job_name: 'techanal-custom'
    static_configs:
      - targets: ['server:8787']
    metrics_path: '/api/v1/ai-engine-performance'
    scrape_interval: 60s
    scrape_timeout: 15s
    honor_labels: true
