name: Compose Validate

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'docker-compose.yml'
      - 'server/**'
      - 'ui/**'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate compose file
        run: docker compose -f docker-compose.yml config

      - name: Build dev images (no cache, no push)
        run: |
          docker build -f server/Dockerfile.dev -t local/server:dev ./server
          docker build -f ui/Dockerfile.dev -t local/ui:dev ./ui

