name: CI with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build and test via Grunt (CI)
        run: pnpm run ci
      - name: Upload UI build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ui-dist
          path: ui/dist

  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint UI (non-blocking)
        run: pnpm --filter ui run lint || true

name: CI with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build and test via Grunt
        run: pnpm run grunt


