name: Release Images to GHCR

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

env:
  REPO_NAME: ${{ github.event.repository.name }}
  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Server image metadata
        id: meta_server
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.OWNER }}/${{ env.REPO_NAME }}-server
          tags: |
            type=sha
            type=ref,event=tag
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Extract UI image metadata
        id: meta_ui
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.OWNER }}/${{ env.REPO_NAME }}-ui
          tags: |
            type=sha
            type=ref,event=tag
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build and push Server image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile.prod
          push: true
          tags: ${{ steps.meta_server.outputs.tags }}
          labels: ${{ steps.meta_server.outputs.labels }}

      - name: Build and push UI image
        uses: docker/build-push-action@v6
        with:
          context: ./ui
          file: ./ui/Dockerfile.prod
          push: true
          tags: ${{ steps.meta_ui.outputs.tags }}
          labels: ${{ steps.meta_ui.outputs.labels }}


